version: "2"

volumes:
  adsfdb:
    external: false

services:
  adsfdb:
    image: mongo:latest
    env_file: ./backend/.env
    environment:
      - DB_NAME=adsfdb
    volumes:
      - ./backend/data:/data/db
    ports:
      - "27017:27017"
    restart: always

  adsfserver:
    build:
      context: ./backend/
      dockerfile: Deploy.Dockerfile
    env_file: ./backend/.env
    environment:
      - APP_ENV=production
    ports:
      - "8080:8080"
    depends_on:
      - adsfdb
    restart: always

  adsfclient:
    build:
      context: ./frontend/
      dockerfile: Deploy.Dockerfile
    environment:
      - API_HOST=http://192.241.214.77:8080
      - DB_NAME=adsfdb
    ports:
      - "80:9000"
    depends_on:
      - adsfserver
    restart: always

  # proxy:
  #   build: ./nginx/.
  #   ports:
  #     - "80:80"
