version: "2"

volumes:
  adsfdb_dev:
    external: false

services:
  adsfdb_dev:
    image: mongo:latest
    env_file: ./backend/.env
    volumes:
      - ./backend/data:/data/db
    ports:
      - "27017:27017"

  adsfserver_dev:
    build: ./backend/.
    env_file: ./backend/.env
    volumes:
      - ~/projects/porfolio_react_redux/backend/src:/app/src
    ports:
      - "8080:8080"
    links:
      - adsfdb_dev

  adsfclient_dev:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ~/projects/porfolio_react_redux/frontend/src:/app/src
      - ~/projects/porfolio_react_redux/frontend/config:/app/config
      - ~/projects/porfolio_react_redux/frontend/package.json:/app/package.json
    ports:
      - "80:3000"
    #environment:
    #  - API_HOST=http://localhost:8080

  # proxy:
  #   build: ./nginx/.
  #   ports:
  #     - "80:80"
  #   volumes:
  #     -
