version: "2"

volumes:
  adsfdb:
    external: false

services:
  adsfdb:
    image: mongo:latest
    env_file: ./backend/.env
    environment:
      - DB_NAME=adsfdb
    volumes:
      - ./backend/data:/data/db
    ports:
      - "27017:27017"
    restart: always

  adsfserver:
    build:
      context: ./backend/
      dockerfile: Prod.Dockerfile
    env_file: ./backend/.env
    environment:
      - APP_ENV=production
    ports:
      - "8080:8080"
    links:
      - adsfdb
    networks:
      - frontend
      - backend
    restart: always

  adsfclient:
    build:
      context: ./frontend/
      dockerfile: Prod.Dockerfile
    environment:
      - API_HOST=http://localhost:8080
      - DB_NAME=adsfdb
    ports:
      - "80:9000"
    links:
      - adsfserver
    networks:
      - frontend
    restart: always

networks:
  frontend:
  backend:
    driver: bridge

  # proxy:
  #   build: ./nginx/.
  #   ports:
  #     - "80:80"
